// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlkvtjnjuqcuankrasxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpsa3Z0am5qdXFjdWFua3Jhc3hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTkyNjcsImV4cCI6MjA2NTUzNTI2N30.uj1pGbeo2mJv5plSdZj11g_LGcVQpcKOBKAFk9Xwh_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);